//"support": "For assistance with making changes please contact ",




langs = {

  "en": {
    "appName": "My Browser Status",
    "appTitle": "This summarizes your browser's readiness for this service.",
    "browser": "All popular browsers are acceptable, IE should be version 11 or higher (available free at <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10+ must be installed and/or activated. Available free at <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "This service requires the IE browser version 7 or higher (available free at <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "IEc": "IE users must enable compatibility view.",
    "Chrome": "There is a known bug with the Chrome browser that will negatively affect your session. Please use another major browser.",
    "Chrome54": "There is a known bug with the Chrome browser that will negatively affect your session. Please use another major browser.",
    "FF31": "There are some known issues with this version. Please use another major browser.",
    "Java": "[<a href='http://javatester.org/version.html' target='_blank'>Version Checker</a>]&ensp;Please make sure you add <span style='font-weight:bold; background-color:yellow;'>http://vaultlearning.com</span> to the exception site list on the java console. Instructions at <a href='https://www.java.com/en/download/exception_sitelist.jsp' target='_blank'>https://www.java.com/en/download/exception_sitelist.jsp</a>.",
    "Ecom": "Ecommerce security and privacy requires that browser security setting TLS 1.2 be enabled. This is the default of all current browsers.",

    "popup": "Popups must be enabled.",
    "support": "For assistance with making changes :",
    "option": "Option",
    "yourStatus": "Your Status",
    "notes": "Notes",
    "browserVersion": "Browser Version",
    "popupsEnabled": "Popups Enabled",
    "cookiesEnabled": "Cookies Enabled",
    "enableCookies": "Cookies Must be enabled",
    "flashEnabled": "Flash Enabled",
    "browserIsIE": "Browser is IE",
    "browserIsIEc": "IE with Compatibility",
    "browserIsChrome": "Chrome Browser",
    "browserIsChrome54": "Chrome Browser 54",
    "browserIsFF31": "Firefox 31.0",
    "javaEnabled": "Java Enabled",
    "ecomReady": "Ecommerce Ready"
  },

  "fr": {
    "appName": "Mon statut de navigateur",
    "appTitle": "Ceci résume les démarches à suivre pour régler votre navigateur.",
    "browser": "Tous les navigateurs populaires sont acceptables, IE doit être de version 11 ou ultérieure (disponible gratuitement à <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10 + doit être installé et/ou activé. Disponible gratuitement à <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "Ce service nécessite la version du navigateur IE 7 ou supérieure (disponible gratuitement à <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).</a>.",
    "IEc": "Les utilisateurs de IE doivent permettre l'affichage de compatibilité.",
    "Chrome": "Il y a un bug connu avec le navigateur Chrome qui affectera négativement votre session. Veuillez utiliser un autre navigateur majeur.",
    "Chrome54": "Il y a un bug connu avec le navigateur Chrome qui affectera négativement votre session. Veuillez utiliser un autre navigateur majeur.",
    "FF31": "Il y a quelques problèmes connus avec cette version. Veuillez utiliser un autre navigateur majeur.",
    "Java": "[<a href='http://javatester.org/version.html' target='_blank'>Version Checker</a>]&ensp;Please make sure you add <span style='font-weight:bold; background-color:yellow;'>http://vaultlearning.com</span> to the exception site list on the java console. Instructions at <a href='https://www.java.com/en/download/exception_sitelist.jsp' target='_blank'>https://www.java.com/en/download/exception_sitelist.jsp</a>.",
    "Ecom": "En raison des mesures de sécurité et de confidentialité requises des transactions électroniques, le paramètre de sécurité du navigateur doit être TLS 1.2. Il s’agit du paramètre par défaut de tous les navigateurs.", 

    "popup": "Fenêtres pop-up doit être activée.",
    "support": "Pour obtenir de l&#39;assistance : ",
    "option": "Option",
    "yourStatus": "Votre statut",
    "notes": "Notes",
    "browserVersion": "Version du navigateur",
    "popupsEnabled": "Popup activé",
    "cookiesEnabled": "Cookies activés",
    "enableCookies": "Les cookies doivent être activés",
    "flashEnabled": "Flash activé",
    "browserIsIE": "Le navigateur est IE",
    "browserIsIEc": "IE avec compatibilité",
    "browserIsChrome": "Navigateur Chrome",
    "browserIsChrome54": "Navigateur Chrome 54",
    "browserIsFF31": "Firefox 31.0",
    "javaEnabled": "Java activé",
    "ecomReady": "Commerce électronique prêt"
  },

  "es": {
    "appName": "Estado de mi navegador",
    "appTitle": "Esto resume la preparación de su navegador para este servicio.",
    "browser": "Todos los navegadores populares son aceptables, es decir debe ser versión 11 o superior (disponible gratis en <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10 + debe ser instalado o activado. Disponible gratis en <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "Este servicio requiere la versión del navegador IE 7 o superior (disponible gratis en <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "IEc": "Los usuarios de IE deben activar la vista de compatibilidad.",
    "Chrome": "Hay un error con el navegador Chrome que afectará negativamente a su sesión. Por favor utilice otro navegador principal.",
    "Chrome54": "Hay un error con el navegador Chrome que afectará negativamente a su sesión. Por favor utilice otro navegador principal.",
    "FF31": "Hay algunos problemas conocidos de esta versión. Por favor utilice otro navegador principal.",
    "Java": "[<a href='http://javatester.org/version.html' target='_blank'>Version Checker</a>]&ensp;Please make sure you add <span style='font-weight:bold; background-color:yellow;'>http://vaultlearning.com</span> to the exception site list on the java console. Instructions at <a href='https://www.java.com/en/download/exception_sitelist.jsp' target='_blank'>https://www.java.com/en/download/exception_sitelist.jsp</a>.",
    "Ecom": "ECommerce seguridad y privacidad que seguridad del navegador requiere habilitar configuración TLS 1.2. Este es el valor predeterminado de todos los navegadores actuales.",

    "popup": "Pop-ups deben estar habilitados.",
    "support": "Para obtener ayuda con cambios, por favor póngase : ",
    "option": "Opción",
    "yourStatus": "Su estado",
    "notes": "Notas",
    "browserVersion": "Versión del navegador",
    "popupsEnabled": "Popups activados",
    "cookiesEnabled": "Cookies activadas",
    "enableCookies": "Deben habilitar las cookies",
    "flashEnabled": "Flash activado",
    "browserIsIE": "Navegador es IE",
    "browserIsIEc": "IE con compatibilidad",
    "browserIsChrome": "Navegador Chrome",
    "browserIsChrome54": "Navegador Chrome 54",
    "browserIsFF31": "Firefox 31.0",
    "javaEnabled": "Habilitado para Java",
    "ecomReady": "eCommerce listo"

  },

  "pt": {
    "appName": "Meu Status de navegador",
    "appTitle": "Isto resume a prontidão do seu navegador para este serviço.",
    "browser": "Todos os browsers populares são aceitáveis, ou seja, deve ser versão 11 ou superior (disponível gratuitamente em <a target='_blank' href='http://www.microsoft.com'> http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10 + deve ser instalado e/ou ativado. Disponível gratuitamente em <a target='_blank' href='http://get.adobe.com/flashplayer/'> http://get.adobe.com/flashplayer</a>. ",
    "IE": "Este serviço requer a versão do navegador IE 7 ou superior (disponível gratuitamente em <a target='_blank' href='http://www.microsoft.com'> http://www.microsoft.com</a>).",
    "IEc": "Os usuários do IE devem habilitar exibição de compatibilidade.",
    "Chrome": "Há um bug conhecido com o navegador Chrome que afetará negativamente sua sessão. Por favor use outro navegador principal. ",
    "Chrome54": "Há um bug conhecido com o navegador Chrome que afetará negativamente sua sessão. Por favor use outro navegador principal. ",
    "FF31": "Existem alguns problemas conhecidos com esta versão. Por favor use outro navegador principal.",
    "Java": "[<a href='http://javatester.org/version.html' target='_blank'>Version Checker</a>]&ensp;Please make sure you add <span style='font-weight:bold; background-color:yellow;'>http://vaultlearning.com</span> to the exception site list on the java console. Instructions at <a href='https://www.java.com/en/download/exception_sitelist.jsp' target='_blank'>https://www.java.com/en/download/exception_sitelist.jsp</a>.",
    "Ecom": "Ecommerce-segurança e privacidade requer a segurança do navegador configuração TLS 1.2 ser habilitada. Este é o padrão de todos os navegadores atuais.",

    "popup": "Pop-ups devem ser ativados.",
    "support": "Para obter assistência com alterações : ",
    "option": "Opção",
    "yourStatus": "Seu Status",
    "notes": "Notas",
    "browserVersion": "Versão do navegador",
    "popupsEnabled": "Pop-ups ativados",
    "cookiesEnabled": "Cookies habilitados",
    "enableCookies": "Os cookies devem ser habilitados",
    "flashEnabled": "Flash habilitado",
    "browserIsIE": "Navegador é IE",
    "browserIsIEc": "IE com compatibilidade",
    "browserIsChrome": "Navegador Chrome",
    "browserIsChrome54": "Navegador Chrome 54",
    "browserIsFF31": "Firefox 31.0",
    "javaEnabled": "Java habilitado",
    "ecomReady": "Ecommerce pronto"
  }

};