langs = {

  "en": {
    "appName": "My Browser Status",
    "appTitle": "This summarizes your browser&#39;s readiness for this service.",
    "browser": "All popular browsers are acceptable, IE should be version 7 or higher (available free at <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10+ must be installed. Available free at <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "This service requires the IE browser version 7 or higher (available free at <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "IEc": "IE users must enable compatibility view.",
    "Chrome": "There is a known bug with the Chrome browser that will negatively affect your session. Please use another major browser.",
    "popup": "Popups must be enabled.",
    "support": "For assistance with making changes please contact ",
    "option": "Option",
    "yourStatus": "Your Status",
    "notes": "Notes",
    "browserVersion": "Browser Version",
    "popupsEnabled": "Popups Enabled",
    "cookiesEnabled": "Cookies Enabled",
    "enableCookies": "Cookies Must be enabled",
    "flashEnabled": "Flash Enabled",
    "browserIsIE": "Browser is IE",
    "browserIsIEc": "IE with Compatibility",
    "browserIsChrome": "Chrome Browser"
  },

  "fr": {
    "appName": "Mon statut de navigateur",
    "appTitle": "Ceci résume les démarches à suivre pour régler votre navigateur.",
    "browser": "Tous les navigateurs populaires sont acceptables, IE doit être de version 7 ou ultérieure (disponible gratuitement à  <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10 + doit être installé. Disponible gratuitement à <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "Ce service nécessite la version du navigateur IE 7 ou supérieure (disponible gratuitement à <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).</a>.",
    "IEc": "Les utilisateurs de IE doivent permettre l'affichage de compatibilité.",
    "Chrome": "Il y a un bug connu avec le navigateur Chrome qui affectera négativement votre session. Veuillez utiliser un autre navigateur majeur.",
    "popup": "Fenêtres pop-up doit être activée.",
    "support": "Pour obtenir de l&#39;assistance, veuillez contacter ",
    "option": "Option",
    "yourStatus": "Votre statut",
    "notes": "Notes",
    "browserVersion": "Version du navigateur",
    "popupsEnabled": "Popup activé",
    "cookiesEnabled": "Cookies activés",
    "enableCookies": "Les cookies doivent être activés",
    "flashEnabled": "Flash activé",
    "browserIsIE": "Le navigateur est IE",
    "browserIsIEc": "IE avec compatibilité",
    "browserIsChrome": "Navigateur Chrome"
  },

  "es": {
    "appName": "Estado de mi navegador",
    "appTitle": "Esto resume la preparación de su navegador para este servicio.",
    "browser": "Todos los navegadores populares son aceptables, es decir debe ser versión 7 o superior (disponible gratis en <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "flash": "Se debe instalar Adobe Flash Player 10 +. Disponible gratis en <a target='_blank' href='http://get.adobe.com/flashplayer/'>http://get.adobe.com/flashplayer</a>.",
    "IE": "Este servicio requiere la versión del navegador IE 7 o superior (disponible gratis en <a target='_blank' href='http://www.microsoft.com'>http://www.microsoft.com</a>).",
    "IEc": "Los usuarios de IE deben activar la vista de compatibilidad.",
    "Chrome": "Hay un error con el navegador Chrome que afectará negativamente a su sesión. Por favor utilice otro navegador principal.",
    "popup": "Pop-ups deben estar habilitados.",
    "support": "Para obtener ayuda con cambios, por favor póngase en contacto con ",
    "option": "Opción",
    "yourStatus": "Su estado",
    "notes": "Notas",
    "browserVersion": "Versión del navegador",
    "popupsEnabled": "Popups activados",
    "cookiesEnabled": "Cookies activadas",
    "enableCookies": "Deben habilitar las cookies",
    "flashEnabled": "Flash activado",
    "browserIsIE": "Navegador es IE",
    "browserIsIEc": "IE con compatibilidad",
    "browserIsChrome": "Navegador Chrome"

  },

  "pt": {
    "appName": "Meu Status de navegador",
    "appTitle": "Isso resume seu navegador &#39; prontidão de s para este serviço.",
    "browser": "Todos os browsers populares são aceitáveis, ou seja, deve ser versão 7 ou superior (disponível gratuitamente em <a target='_blank' href='http://www.microsoft.com'> http://www.microsoft.com</a>).",
    "flash": "Adobe Flash Player 10 + deve ser instalado. Disponível gratuitamente em <a target='_blank' href='http://get.adobe.com/flashplayer/'> http://get.adobe.com/flashplayer</a>. ",
    "IE": "Este serviço requer a versão do navegador IE 7 ou superior (disponível gratuitamente em <a target='_blank' href='http://www.microsoft.com'> http://www.microsoft.com</a>).",
    "IEc": "Os usuários do IE devem habilitar exibição de compatibilidade.",
    "Chrome": "Há um bug conhecido com o navegador Chrome que afetará negativamente sua sessão. Por favor use outro navegador principal. ",
    "popup": "Pop-ups devem ser ativados.",
    "support": "Para obter assistência com alterações entre em contato ",
    "option": "Opção",
    "yourStatus": "Seu Status",
    "notes": "Notas",
    "browserVersion": "Versão do navegador",
    "popupsEnabled": "Pop-ups ativados",
    "cookiesEnabled": "Cookies habilitados",
    "enableCookies": "Os cookies devem ser habilitados",
    "flashEnabled": "Flash habilitado",
    "browserIsIE": "Navegador é IE",
    "browserIsIEc": "IE com compatibilidade",
    "browserIsChrome": "Navegador Chrome"
  }

};