//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace vubiz.apps.com {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="v8serverSoap", Namespace="http://vubiz.com/")]
    public partial class v8server : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EcomExtendOperationCompleted;
        
        private System.Threading.SendOrPostCallback autoEnrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback autoEnrollWsOperationCompleted;
        
        private System.Threading.SendOrPostCallback autoSignInOperationCompleted;
        
        private System.Threading.SendOrPostCallback vuEcommerceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ssoMembGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback ssoMembIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ssoMembNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ssoMembId2OperationCompleted;
        
        private System.Threading.SendOrPostCallback custTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback caamEnrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfibAuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfibSignInOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfibEnrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfibIsMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback enrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback profilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ecommerceReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback isGovActivityReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback isGovActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback learnerReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback learnerReport2OperationCompleted;
        
        private System.Threading.SendOrPostCallback learnerActivityReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback programActivityDetailsReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public v8server() {
            this.Url = global::vubiz.apps.Properties.Settings.Default.vubiz_apps_com_v8server;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EcomExtendCompletedEventHandler EcomExtendCompleted;
        
        /// <remarks/>
        public event autoEnrollCompletedEventHandler autoEnrollCompleted;
        
        /// <remarks/>
        public event autoEnrollWsCompletedEventHandler autoEnrollWsCompleted;
        
        /// <remarks/>
        public event autoSignInCompletedEventHandler autoSignInCompleted;
        
        /// <remarks/>
        public event vuEcommerceCompletedEventHandler vuEcommerceCompleted;
        
        /// <remarks/>
        public event ssoMembGuidCompletedEventHandler ssoMembGuidCompleted;
        
        /// <remarks/>
        public event ssoMembIdCompletedEventHandler ssoMembIdCompleted;
        
        /// <remarks/>
        public event ssoMembNoCompletedEventHandler ssoMembNoCompleted;
        
        /// <remarks/>
        public event ssoMembId2CompletedEventHandler ssoMembId2Completed;
        
        /// <remarks/>
        public event custTitleCompletedEventHandler custTitleCompleted;
        
        /// <remarks/>
        public event caamEnrollCompletedEventHandler caamEnrollCompleted;
        
        /// <remarks/>
        public event cfibAuthenticateCompletedEventHandler cfibAuthenticateCompleted;
        
        /// <remarks/>
        public event cfibSignInCompletedEventHandler cfibSignInCompleted;
        
        /// <remarks/>
        public event cfibEnrollCompletedEventHandler cfibEnrollCompleted;
        
        /// <remarks/>
        public event cfibIsMemberCompletedEventHandler cfibIsMemberCompleted;
        
        /// <remarks/>
        public event enrollCompletedEventHandler enrollCompleted;
        
        /// <remarks/>
        public event isMemberCompletedEventHandler isMemberCompleted;
        
        /// <remarks/>
        public event profilesCompletedEventHandler profilesCompleted;
        
        /// <remarks/>
        public event translateCompletedEventHandler translateCompleted;
        
        /// <remarks/>
        public event translateUpdateCompletedEventHandler translateUpdateCompleted;
        
        /// <remarks/>
        public event ecommerceReportCompletedEventHandler ecommerceReportCompleted;
        
        /// <remarks/>
        public event isGovActivityReportCompletedEventHandler isGovActivityReportCompleted;
        
        /// <remarks/>
        public event isGovActivityCompletedEventHandler isGovActivityCompleted;
        
        /// <remarks/>
        public event learnerReportCompletedEventHandler learnerReportCompleted;
        
        /// <remarks/>
        public event learnerReport2CompletedEventHandler learnerReport2Completed;
        
        /// <remarks/>
        public event learnerActivityReportCompletedEventHandler learnerActivityReportCompleted;
        
        /// <remarks/>
        public event programActivityDetailsReportCompletedEventHandler programActivityDetailsReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/EcomExtend", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EcomExtend(string custGuid, string learnerId, string programId, string noDays) {
            object[] results = this.Invoke("EcomExtend", new object[] {
                        custGuid,
                        learnerId,
                        programId,
                        noDays});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EcomExtendAsync(string custGuid, string learnerId, string programId, string noDays) {
            this.EcomExtendAsync(custGuid, learnerId, programId, noDays, null);
        }
        
        /// <remarks/>
        public void EcomExtendAsync(string custGuid, string learnerId, string programId, string noDays, object userState) {
            if ((this.EcomExtendOperationCompleted == null)) {
                this.EcomExtendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEcomExtendOperationCompleted);
            }
            this.InvokeAsync("EcomExtend", new object[] {
                        custGuid,
                        learnerId,
                        programId,
                        noDays}, this.EcomExtendOperationCompleted, userState);
        }
        
        private void OnEcomExtendOperationCompleted(object arg) {
            if ((this.EcomExtendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EcomExtendCompleted(this, new EcomExtendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/autoEnroll", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string autoEnroll(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo) {
            object[] results = this.Invoke("autoEnroll", new object[] {
                        custGuid,
                        membId,
                        membFirstName,
                        membLastName,
                        membEmail,
                        membMemo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void autoEnrollAsync(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo) {
            this.autoEnrollAsync(custGuid, membId, membFirstName, membLastName, membEmail, membMemo, null);
        }
        
        /// <remarks/>
        public void autoEnrollAsync(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo, object userState) {
            if ((this.autoEnrollOperationCompleted == null)) {
                this.autoEnrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautoEnrollOperationCompleted);
            }
            this.InvokeAsync("autoEnroll", new object[] {
                        custGuid,
                        membId,
                        membFirstName,
                        membLastName,
                        membEmail,
                        membMemo}, this.autoEnrollOperationCompleted, userState);
        }
        
        private void OnautoEnrollOperationCompleted(object arg) {
            if ((this.autoEnrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autoEnrollCompleted(this, new autoEnrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/autoEnrollWs", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string autoEnrollWs(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo, string membPrograms, bool membActive) {
            object[] results = this.Invoke("autoEnrollWs", new object[] {
                        custGuid,
                        membId,
                        membFirstName,
                        membLastName,
                        membEmail,
                        membMemo,
                        membPrograms,
                        membActive});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void autoEnrollWsAsync(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo, string membPrograms, bool membActive) {
            this.autoEnrollWsAsync(custGuid, membId, membFirstName, membLastName, membEmail, membMemo, membPrograms, membActive, null);
        }
        
        /// <remarks/>
        public void autoEnrollWsAsync(string custGuid, string membId, string membFirstName, string membLastName, string membEmail, string membMemo, string membPrograms, bool membActive, object userState) {
            if ((this.autoEnrollWsOperationCompleted == null)) {
                this.autoEnrollWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautoEnrollWsOperationCompleted);
            }
            this.InvokeAsync("autoEnrollWs", new object[] {
                        custGuid,
                        membId,
                        membFirstName,
                        membLastName,
                        membEmail,
                        membMemo,
                        membPrograms,
                        membActive}, this.autoEnrollWsOperationCompleted, userState);
        }
        
        private void OnautoEnrollWsOperationCompleted(object arg) {
            if ((this.autoEnrollWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autoEnrollWsCompleted(this, new autoEnrollWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/autoSignIn", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string autoSignIn(string custAcctId, string membId, string membPassword) {
            object[] results = this.Invoke("autoSignIn", new object[] {
                        custAcctId,
                        membId,
                        membPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void autoSignInAsync(string custAcctId, string membId, string membPassword) {
            this.autoSignInAsync(custAcctId, membId, membPassword, null);
        }
        
        /// <remarks/>
        public void autoSignInAsync(string custAcctId, string membId, string membPassword, object userState) {
            if ((this.autoSignInOperationCompleted == null)) {
                this.autoSignInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautoSignInOperationCompleted);
            }
            this.InvokeAsync("autoSignIn", new object[] {
                        custAcctId,
                        membId,
                        membPassword}, this.autoSignInOperationCompleted, userState);
        }
        
        private void OnautoSignInOperationCompleted(object arg) {
            if ((this.autoSignInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autoSignInCompleted(this, new autoSignInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/vuEcommerce", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string vuEcommerce(string token, string logGuid) {
            object[] results = this.Invoke("vuEcommerce", new object[] {
                        token,
                        logGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vuEcommerceAsync(string token, string logGuid) {
            this.vuEcommerceAsync(token, logGuid, null);
        }
        
        /// <remarks/>
        public void vuEcommerceAsync(string token, string logGuid, object userState) {
            if ((this.vuEcommerceOperationCompleted == null)) {
                this.vuEcommerceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvuEcommerceOperationCompleted);
            }
            this.InvokeAsync("vuEcommerce", new object[] {
                        token,
                        logGuid}, this.vuEcommerceOperationCompleted, userState);
        }
        
        private void OnvuEcommerceOperationCompleted(object arg) {
            if ((this.vuEcommerceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vuEcommerceCompleted(this, new vuEcommerceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/ssoMembGuid", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ssoMembGuid(string membGuid) {
            object[] results = this.Invoke("ssoMembGuid", new object[] {
                        membGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ssoMembGuidAsync(string membGuid) {
            this.ssoMembGuidAsync(membGuid, null);
        }
        
        /// <remarks/>
        public void ssoMembGuidAsync(string membGuid, object userState) {
            if ((this.ssoMembGuidOperationCompleted == null)) {
                this.ssoMembGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnssoMembGuidOperationCompleted);
            }
            this.InvokeAsync("ssoMembGuid", new object[] {
                        membGuid}, this.ssoMembGuidOperationCompleted, userState);
        }
        
        private void OnssoMembGuidOperationCompleted(object arg) {
            if ((this.ssoMembGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ssoMembGuidCompleted(this, new ssoMembGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/ssoMembId", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ssoMembId(string custId, string membId) {
            object[] results = this.Invoke("ssoMembId", new object[] {
                        custId,
                        membId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ssoMembIdAsync(string custId, string membId) {
            this.ssoMembIdAsync(custId, membId, null);
        }
        
        /// <remarks/>
        public void ssoMembIdAsync(string custId, string membId, object userState) {
            if ((this.ssoMembIdOperationCompleted == null)) {
                this.ssoMembIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnssoMembIdOperationCompleted);
            }
            this.InvokeAsync("ssoMembId", new object[] {
                        custId,
                        membId}, this.ssoMembIdOperationCompleted, userState);
        }
        
        private void OnssoMembIdOperationCompleted(object arg) {
            if ((this.ssoMembIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ssoMembIdCompleted(this, new ssoMembIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/ssoMembNo", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ssoMembNo(string membNo) {
            object[] results = this.Invoke("ssoMembNo", new object[] {
                        membNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ssoMembNoAsync(string membNo) {
            this.ssoMembNoAsync(membNo, null);
        }
        
        /// <remarks/>
        public void ssoMembNoAsync(string membNo, object userState) {
            if ((this.ssoMembNoOperationCompleted == null)) {
                this.ssoMembNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnssoMembNoOperationCompleted);
            }
            this.InvokeAsync("ssoMembNo", new object[] {
                        membNo}, this.ssoMembNoOperationCompleted, userState);
        }
        
        private void OnssoMembNoOperationCompleted(object arg) {
            if ((this.ssoMembNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ssoMembNoCompleted(this, new ssoMembNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/ssoMembId2", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ssoMembId2(string custGuid, string membId) {
            object[] results = this.Invoke("ssoMembId2", new object[] {
                        custGuid,
                        membId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ssoMembId2Async(string custGuid, string membId) {
            this.ssoMembId2Async(custGuid, membId, null);
        }
        
        /// <remarks/>
        public void ssoMembId2Async(string custGuid, string membId, object userState) {
            if ((this.ssoMembId2OperationCompleted == null)) {
                this.ssoMembId2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnssoMembId2OperationCompleted);
            }
            this.InvokeAsync("ssoMembId2", new object[] {
                        custGuid,
                        membId}, this.ssoMembId2OperationCompleted, userState);
        }
        
        private void OnssoMembId2OperationCompleted(object arg) {
            if ((this.ssoMembId2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ssoMembId2Completed(this, new ssoMembId2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/custTitle", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string custTitle(string custId) {
            object[] results = this.Invoke("custTitle", new object[] {
                        custId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void custTitleAsync(string custId) {
            this.custTitleAsync(custId, null);
        }
        
        /// <remarks/>
        public void custTitleAsync(string custId, object userState) {
            if ((this.custTitleOperationCompleted == null)) {
                this.custTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustTitleOperationCompleted);
            }
            this.InvokeAsync("custTitle", new object[] {
                        custId}, this.custTitleOperationCompleted, userState);
        }
        
        private void OncustTitleOperationCompleted(object arg) {
            if ((this.custTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.custTitleCompleted(this, new custTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/caamEnroll", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string caamEnroll(string custGuid, string membId) {
            object[] results = this.Invoke("caamEnroll", new object[] {
                        custGuid,
                        membId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void caamEnrollAsync(string custGuid, string membId) {
            this.caamEnrollAsync(custGuid, membId, null);
        }
        
        /// <remarks/>
        public void caamEnrollAsync(string custGuid, string membId, object userState) {
            if ((this.caamEnrollOperationCompleted == null)) {
                this.caamEnrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OncaamEnrollOperationCompleted);
            }
            this.InvokeAsync("caamEnroll", new object[] {
                        custGuid,
                        membId}, this.caamEnrollOperationCompleted, userState);
        }
        
        private void OncaamEnrollOperationCompleted(object arg) {
            if ((this.caamEnrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.caamEnrollCompleted(this, new caamEnrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/cfibAuthenticate", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cfibAuthenticate(string profile, string membEmailEncrypted, string membPasswordEncrypted) {
            object[] results = this.Invoke("cfibAuthenticate", new object[] {
                        profile,
                        membEmailEncrypted,
                        membPasswordEncrypted});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfibAuthenticateAsync(string profile, string membEmailEncrypted, string membPasswordEncrypted) {
            this.cfibAuthenticateAsync(profile, membEmailEncrypted, membPasswordEncrypted, null);
        }
        
        /// <remarks/>
        public void cfibAuthenticateAsync(string profile, string membEmailEncrypted, string membPasswordEncrypted, object userState) {
            if ((this.cfibAuthenticateOperationCompleted == null)) {
                this.cfibAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfibAuthenticateOperationCompleted);
            }
            this.InvokeAsync("cfibAuthenticate", new object[] {
                        profile,
                        membEmailEncrypted,
                        membPasswordEncrypted}, this.cfibAuthenticateOperationCompleted, userState);
        }
        
        private void OncfibAuthenticateOperationCompleted(object arg) {
            if ((this.cfibAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfibAuthenticateCompleted(this, new cfibAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/cfibSignIn", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cfibSignIn(string profile, string membEmail, string membPassword) {
            object[] results = this.Invoke("cfibSignIn", new object[] {
                        profile,
                        membEmail,
                        membPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfibSignInAsync(string profile, string membEmail, string membPassword) {
            this.cfibSignInAsync(profile, membEmail, membPassword, null);
        }
        
        /// <remarks/>
        public void cfibSignInAsync(string profile, string membEmail, string membPassword, object userState) {
            if ((this.cfibSignInOperationCompleted == null)) {
                this.cfibSignInOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfibSignInOperationCompleted);
            }
            this.InvokeAsync("cfibSignIn", new object[] {
                        profile,
                        membEmail,
                        membPassword}, this.cfibSignInOperationCompleted, userState);
        }
        
        private void OncfibSignInOperationCompleted(object arg) {
            if ((this.cfibSignInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfibSignInCompleted(this, new cfibSignInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/cfibEnroll", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cfibEnroll(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization, string membType, string membMemo) {
            object[] results = this.Invoke("cfibEnroll", new object[] {
                        custId,
                        membEmail,
                        membPassword,
                        membFirstName,
                        membLastName,
                        membOrganization,
                        membType,
                        membMemo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfibEnrollAsync(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization, string membType, string membMemo) {
            this.cfibEnrollAsync(custId, membEmail, membPassword, membFirstName, membLastName, membOrganization, membType, membMemo, null);
        }
        
        /// <remarks/>
        public void cfibEnrollAsync(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization, string membType, string membMemo, object userState) {
            if ((this.cfibEnrollOperationCompleted == null)) {
                this.cfibEnrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfibEnrollOperationCompleted);
            }
            this.InvokeAsync("cfibEnroll", new object[] {
                        custId,
                        membEmail,
                        membPassword,
                        membFirstName,
                        membLastName,
                        membOrganization,
                        membType,
                        membMemo}, this.cfibEnrollOperationCompleted, userState);
        }
        
        private void OncfibEnrollOperationCompleted(object arg) {
            if ((this.cfibEnrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfibEnrollCompleted(this, new cfibEnrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/cfibIsMember", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cfibIsMember(string custId, string membOrganization, string membEmail) {
            object[] results = this.Invoke("cfibIsMember", new object[] {
                        custId,
                        membOrganization,
                        membEmail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfibIsMemberAsync(string custId, string membOrganization, string membEmail) {
            this.cfibIsMemberAsync(custId, membOrganization, membEmail, null);
        }
        
        /// <remarks/>
        public void cfibIsMemberAsync(string custId, string membOrganization, string membEmail, object userState) {
            if ((this.cfibIsMemberOperationCompleted == null)) {
                this.cfibIsMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfibIsMemberOperationCompleted);
            }
            this.InvokeAsync("cfibIsMember", new object[] {
                        custId,
                        membOrganization,
                        membEmail}, this.cfibIsMemberOperationCompleted, userState);
        }
        
        private void OncfibIsMemberOperationCompleted(object arg) {
            if ((this.cfibIsMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfibIsMemberCompleted(this, new cfibIsMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/enroll", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string enroll(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization) {
            object[] results = this.Invoke("enroll", new object[] {
                        custId,
                        membEmail,
                        membPassword,
                        membFirstName,
                        membLastName,
                        membOrganization});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void enrollAsync(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization) {
            this.enrollAsync(custId, membEmail, membPassword, membFirstName, membLastName, membOrganization, null);
        }
        
        /// <remarks/>
        public void enrollAsync(string custId, string membEmail, string membPassword, string membFirstName, string membLastName, string membOrganization, object userState) {
            if ((this.enrollOperationCompleted == null)) {
                this.enrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenrollOperationCompleted);
            }
            this.InvokeAsync("enroll", new object[] {
                        custId,
                        membEmail,
                        membPassword,
                        membFirstName,
                        membLastName,
                        membOrganization}, this.enrollOperationCompleted, userState);
        }
        
        private void OnenrollOperationCompleted(object arg) {
            if ((this.enrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enrollCompleted(this, new enrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/isMember", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string isMember(string custId, string membId) {
            object[] results = this.Invoke("isMember", new object[] {
                        custId,
                        membId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberAsync(string custId, string membId) {
            this.isMemberAsync(custId, membId, null);
        }
        
        /// <remarks/>
        public void isMemberAsync(string custId, string membId, object userState) {
            if ((this.isMemberOperationCompleted == null)) {
                this.isMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOperationCompleted);
            }
            this.InvokeAsync("isMember", new object[] {
                        custId,
                        membId}, this.isMemberOperationCompleted, userState);
        }
        
        private void OnisMemberOperationCompleted(object arg) {
            if ((this.isMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberCompleted(this, new isMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/profiles", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string profiles(string alias) {
            object[] results = this.Invoke("profiles", new object[] {
                        alias});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void profilesAsync(string alias) {
            this.profilesAsync(alias, null);
        }
        
        /// <remarks/>
        public void profilesAsync(string alias, object userState) {
            if ((this.profilesOperationCompleted == null)) {
                this.profilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprofilesOperationCompleted);
            }
            this.InvokeAsync("profiles", new object[] {
                        alias}, this.profilesOperationCompleted, userState);
        }
        
        private void OnprofilesOperationCompleted(object arg) {
            if ((this.profilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.profilesCompleted(this, new profilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/translate", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string translate(string phrase, string lang) {
            object[] results = this.Invoke("translate", new object[] {
                        phrase,
                        lang});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void translateAsync(string phrase, string lang) {
            this.translateAsync(phrase, lang, null);
        }
        
        /// <remarks/>
        public void translateAsync(string phrase, string lang, object userState) {
            if ((this.translateOperationCompleted == null)) {
                this.translateOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateOperationCompleted);
            }
            this.InvokeAsync("translate", new object[] {
                        phrase,
                        lang}, this.translateOperationCompleted, userState);
        }
        
        private void OntranslateOperationCompleted(object arg) {
            if ((this.translateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateCompleted(this, new translateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/translateUpdate", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string translateUpdate(string phraseIn, string lang, string phraseEx) {
            object[] results = this.Invoke("translateUpdate", new object[] {
                        phraseIn,
                        lang,
                        phraseEx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void translateUpdateAsync(string phraseIn, string lang, string phraseEx) {
            this.translateUpdateAsync(phraseIn, lang, phraseEx, null);
        }
        
        /// <remarks/>
        public void translateUpdateAsync(string phraseIn, string lang, string phraseEx, object userState) {
            if ((this.translateUpdateOperationCompleted == null)) {
                this.translateUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateUpdateOperationCompleted);
            }
            this.InvokeAsync("translateUpdate", new object[] {
                        phraseIn,
                        lang,
                        phraseEx}, this.translateUpdateOperationCompleted, userState);
        }
        
        private void OntranslateUpdateOperationCompleted(object arg) {
            if ((this.translateUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateUpdateCompleted(this, new translateUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/ecommerceReport", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ecommerceReport(string cust, string strDate, string endDate, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("ecommerceReport", new object[] {
                        cust,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ecommerceReportAsync(string cust, string strDate, string endDate, string membNo, string lang, string fileName) {
            this.ecommerceReportAsync(cust, strDate, endDate, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void ecommerceReportAsync(string cust, string strDate, string endDate, string membNo, string lang, string fileName, object userState) {
            if ((this.ecommerceReportOperationCompleted == null)) {
                this.ecommerceReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnecommerceReportOperationCompleted);
            }
            this.InvokeAsync("ecommerceReport", new object[] {
                        cust,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName}, this.ecommerceReportOperationCompleted, userState);
        }
        
        private void OnecommerceReportOperationCompleted(object arg) {
            if ((this.ecommerceReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ecommerceReportCompleted(this, new ecommerceReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/isGovActivityReport", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int isGovActivityReport(string organizations, string strDate, string endDate, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("isGovActivityReport", new object[] {
                        organizations,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void isGovActivityReportAsync(string organizations, string strDate, string endDate, string membNo, string lang, string fileName) {
            this.isGovActivityReportAsync(organizations, strDate, endDate, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void isGovActivityReportAsync(string organizations, string strDate, string endDate, string membNo, string lang, string fileName, object userState) {
            if ((this.isGovActivityReportOperationCompleted == null)) {
                this.isGovActivityReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisGovActivityReportOperationCompleted);
            }
            this.InvokeAsync("isGovActivityReport", new object[] {
                        organizations,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName}, this.isGovActivityReportOperationCompleted, userState);
        }
        
        private void OnisGovActivityReportOperationCompleted(object arg) {
            if ((this.isGovActivityReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isGovActivityReportCompleted(this, new isGovActivityReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/isGovActivity", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int isGovActivity(string organizations, string strDate, string endDate, int repType, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("isGovActivity", new object[] {
                        organizations,
                        strDate,
                        endDate,
                        repType,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void isGovActivityAsync(string organizations, string strDate, string endDate, int repType, string membNo, string lang, string fileName) {
            this.isGovActivityAsync(organizations, strDate, endDate, repType, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void isGovActivityAsync(string organizations, string strDate, string endDate, int repType, string membNo, string lang, string fileName, object userState) {
            if ((this.isGovActivityOperationCompleted == null)) {
                this.isGovActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisGovActivityOperationCompleted);
            }
            this.InvokeAsync("isGovActivity", new object[] {
                        organizations,
                        strDate,
                        endDate,
                        repType,
                        membNo,
                        lang,
                        fileName}, this.isGovActivityOperationCompleted, userState);
        }
        
        private void OnisGovActivityOperationCompleted(object arg) {
            if ((this.isGovActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isGovActivityCompleted(this, new isGovActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/learnerReport", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int learnerReport(string custId, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("learnerReport", new object[] {
                        custId,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void learnerReportAsync(string custId, string membNo, string lang, string fileName) {
            this.learnerReportAsync(custId, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void learnerReportAsync(string custId, string membNo, string lang, string fileName, object userState) {
            if ((this.learnerReportOperationCompleted == null)) {
                this.learnerReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlearnerReportOperationCompleted);
            }
            this.InvokeAsync("learnerReport", new object[] {
                        custId,
                        membNo,
                        lang,
                        fileName}, this.learnerReportOperationCompleted, userState);
        }
        
        private void OnlearnerReportOperationCompleted(object arg) {
            if ((this.learnerReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.learnerReportCompleted(this, new learnerReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/learnerReport2", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int learnerReport2(string custId, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("learnerReport2", new object[] {
                        custId,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void learnerReport2Async(string custId, string membNo, string lang, string fileName) {
            this.learnerReport2Async(custId, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void learnerReport2Async(string custId, string membNo, string lang, string fileName, object userState) {
            if ((this.learnerReport2OperationCompleted == null)) {
                this.learnerReport2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnlearnerReport2OperationCompleted);
            }
            this.InvokeAsync("learnerReport2", new object[] {
                        custId,
                        membNo,
                        lang,
                        fileName}, this.learnerReport2OperationCompleted, userState);
        }
        
        private void OnlearnerReport2OperationCompleted(object arg) {
            if ((this.learnerReport2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.learnerReport2Completed(this, new learnerReport2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/learnerActivityReport", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int learnerActivityReport(string custId, int completed, int guests, string strDate, string endDate, string membNo, string lang, string fileName, int type) {
            object[] results = this.Invoke("learnerActivityReport", new object[] {
                        custId,
                        completed,
                        guests,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName,
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void learnerActivityReportAsync(string custId, int completed, int guests, string strDate, string endDate, string membNo, string lang, string fileName, int type) {
            this.learnerActivityReportAsync(custId, completed, guests, strDate, endDate, membNo, lang, fileName, type, null);
        }
        
        /// <remarks/>
        public void learnerActivityReportAsync(string custId, int completed, int guests, string strDate, string endDate, string membNo, string lang, string fileName, int type, object userState) {
            if ((this.learnerActivityReportOperationCompleted == null)) {
                this.learnerActivityReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlearnerActivityReportOperationCompleted);
            }
            this.InvokeAsync("learnerActivityReport", new object[] {
                        custId,
                        completed,
                        guests,
                        strDate,
                        endDate,
                        membNo,
                        lang,
                        fileName,
                        type}, this.learnerActivityReportOperationCompleted, userState);
        }
        
        private void OnlearnerActivityReportOperationCompleted(object arg) {
            if ((this.learnerActivityReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.learnerActivityReportCompleted(this, new learnerActivityReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vubiz.com/programActivityDetailsReport", RequestNamespace="http://vubiz.com/", ResponseNamespace="http://vubiz.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int programActivityDetailsReport(string custId, string strDate, string endDate, string membId, string membNo, string lang, string fileName) {
            object[] results = this.Invoke("programActivityDetailsReport", new object[] {
                        custId,
                        strDate,
                        endDate,
                        membId,
                        membNo,
                        lang,
                        fileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void programActivityDetailsReportAsync(string custId, string strDate, string endDate, string membId, string membNo, string lang, string fileName) {
            this.programActivityDetailsReportAsync(custId, strDate, endDate, membId, membNo, lang, fileName, null);
        }
        
        /// <remarks/>
        public void programActivityDetailsReportAsync(string custId, string strDate, string endDate, string membId, string membNo, string lang, string fileName, object userState) {
            if ((this.programActivityDetailsReportOperationCompleted == null)) {
                this.programActivityDetailsReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprogramActivityDetailsReportOperationCompleted);
            }
            this.InvokeAsync("programActivityDetailsReport", new object[] {
                        custId,
                        strDate,
                        endDate,
                        membId,
                        membNo,
                        lang,
                        fileName}, this.programActivityDetailsReportOperationCompleted, userState);
        }
        
        private void OnprogramActivityDetailsReportOperationCompleted(object arg) {
            if ((this.programActivityDetailsReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.programActivityDetailsReportCompleted(this, new programActivityDetailsReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EcomExtendCompletedEventHandler(object sender, EcomExtendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EcomExtendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EcomExtendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void autoEnrollCompletedEventHandler(object sender, autoEnrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autoEnrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autoEnrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void autoEnrollWsCompletedEventHandler(object sender, autoEnrollWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autoEnrollWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autoEnrollWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void autoSignInCompletedEventHandler(object sender, autoSignInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autoSignInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autoSignInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void vuEcommerceCompletedEventHandler(object sender, vuEcommerceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vuEcommerceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vuEcommerceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ssoMembGuidCompletedEventHandler(object sender, ssoMembGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ssoMembGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ssoMembGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ssoMembIdCompletedEventHandler(object sender, ssoMembIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ssoMembIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ssoMembIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ssoMembNoCompletedEventHandler(object sender, ssoMembNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ssoMembNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ssoMembNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ssoMembId2CompletedEventHandler(object sender, ssoMembId2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ssoMembId2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ssoMembId2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void custTitleCompletedEventHandler(object sender, custTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class custTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal custTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void caamEnrollCompletedEventHandler(object sender, caamEnrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class caamEnrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal caamEnrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void cfibAuthenticateCompletedEventHandler(object sender, cfibAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfibAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfibAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void cfibSignInCompletedEventHandler(object sender, cfibSignInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfibSignInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfibSignInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void cfibEnrollCompletedEventHandler(object sender, cfibEnrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfibEnrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfibEnrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void cfibIsMemberCompletedEventHandler(object sender, cfibIsMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfibIsMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfibIsMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void enrollCompletedEventHandler(object sender, enrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void isMemberCompletedEventHandler(object sender, isMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void profilesCompletedEventHandler(object sender, profilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class profilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal profilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void translateCompletedEventHandler(object sender, translateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void translateUpdateCompletedEventHandler(object sender, translateUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ecommerceReportCompletedEventHandler(object sender, ecommerceReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ecommerceReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ecommerceReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void isGovActivityReportCompletedEventHandler(object sender, isGovActivityReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isGovActivityReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isGovActivityReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void isGovActivityCompletedEventHandler(object sender, isGovActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isGovActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isGovActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void learnerReportCompletedEventHandler(object sender, learnerReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class learnerReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal learnerReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void learnerReport2CompletedEventHandler(object sender, learnerReport2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class learnerReport2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal learnerReport2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void learnerActivityReportCompletedEventHandler(object sender, learnerActivityReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class learnerActivityReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal learnerActivityReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void programActivityDetailsReportCompletedEventHandler(object sender, programActivityDetailsReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class programActivityDetailsReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal programActivityDetailsReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591